"""One test per real bug, plus the invariant.

    python test_layout.py

No pytest, no network, no downloaded corpus -- the fixtures are generated by
`synth.py` in memory. Runs in about two seconds.

The last section, `verify_suite_is_not_decorative`, re-installs the *previous*
version of each fixed function and asserts the suite catches it. A test suite
that passes on the code it was written against proves nothing.
"""

import statistics
import sys

import fitz

import layout
import metrics
import synth
import tables

_results = []


def check(name):
    def wrap(fn):
        _results.append((name, fn))
        return fn
    return wrap


def build(layouts, seed=42):
    """A PDF in a temp file plus its ground truth, as (doc, truth)."""
    import os
    import tempfile
    handle, path = tempfile.mkstemp(suffix=".pdf")
    os.close(handle)
    truth = synth.build_document(path, layouts, seed=seed)
    doc = fitz.open(path)
    doc._temp_path = path
    return doc, truth


def analyse(layouts, seed=42, page=0):
    doc, truth = build(layouts, seed)
    try:
        elements, stats = layout.analyse_page(doc[page])
    finally:
        doc.close()
    return elements, stats, truth[page]


def flow(elements):
    return sorted((e for e in elements if e.order), key=lambda e: e.order)


# --------------------------------------------------------------------------
# THE INVARIANT
# --------------------------------------------------------------------------

@check("INVARIANT: every character on the page lands in some element")
def _():
    for kind in synth.LAYOUTS:
        elements, stats, _ = analyse((kind,))
        assert stats["coverage"] >= 0.999, \
            f"{kind}: coverage {stats['coverage']} -- text was dropped silently"


@check("INVARIANT: reading order is a total order with no gaps")
def _():
    elements, _, _ = analyse(("two-column",))
    orders = [e.order for e in elements if e.order]
    assert sorted(orders) == list(range(1, len(orders) + 1)), orders


@check("running heads stay out of the reading flow")
def _():
    elements, _, _ = analyse(("single",))
    running = [e for e in elements if e.type in ("header", "footer")]
    assert running, "no header/footer found at all"
    assert all(e.order == 0 for e in running)
    # ...and are still present, because dropping them would break coverage.
    assert any(e.text.strip() for e in running)


# --------------------------------------------------------------------------
# reading order
# --------------------------------------------------------------------------

@check("a two-column page reads down one column then the other")
def _():
    # THE bug the XY-cut axis choice was fixed for. Two earlier versions failed
    # here: horizontal-first interleaved every page, and widest-gap-wins failed
    # whenever both columns broke a paragraph at the same height.
    for seed in (42, 43, 44, 45, 46, 47):
        elements, _, truth = analyse(("two-column",), seed=seed)
        score = metrics.score_page(truth, elements)
        assert score["order_tau"] > 0.99, \
            f"seed {seed}: tau {score['order_tau']}, columns interleaved"


@check("a full-width title above two columns needs no special case")
def _():
    elements, _, _ = analyse(("two-column",))
    ordered = flow(elements)
    assert ordered[0].type == "title", [e.type for e in ordered[:3]]
    # everything in column 0 comes before everything in column 1
    columns = [e.column for e in ordered[1:]]
    assert columns == sorted(columns), columns


@check("the naive top-to-bottom order is measurably wrong here")
def _():
    # If PyMuPDF's own sort=True scored as well as this project on the pages
    # this project exists for, the project would not be worth having.
    doc, truth = build(("two-column",), seed=43)
    try:
        page = doc[0]
        ours, _ = layout.analyse_page(page)
        naive = [_Simple(b[:4], i) for i, b in
                 enumerate(page.get_text("blocks", sort=True), start=1)
                 if str(b[4]).strip()]
    finally:
        doc.close()
    assert metrics.score_page(truth[0], ours)["order_tau"] > \
        metrics.score_page(truth[0], naive)["order_tau"] + 0.2


class _Simple:
    def __init__(self, bbox, order):
        self.bbox, self.order, self.type, self.text = bbox, order, "untyped", ""


# --------------------------------------------------------------------------
# columns
# --------------------------------------------------------------------------

@check("a table's internal whitespace is not a column gutter")
def _():
    # A real bug: the gutter test asked "is this x-slice empty for most of the
    # page height", and the whitespace between an unruled table's own columns
    # is. The page went two-column, the table was analysed one column at a
    # time, and came out 5x2 with its first column emitted as paragraphs.
    elements, stats, _ = analyse(("unruled-table",), seed=5)
    assert stats["columns"] == 1, f"{stats['columns']} columns on a 1-column page"


@check("a single-column page is never split")
def _():
    for kind in ("single", "list", "figure-table"):
        for seed in (42, 51, 60):
            _, stats, _ = analyse((kind,), seed=seed)
            assert stats["columns"] == 1, f"{kind}/{seed}: {stats['columns']}"


@check("a genuine two-column page IS split")
def _():
    for seed in (42, 43, 44):
        _, stats, _ = analyse(("two-column",), seed=seed)
        assert stats["columns"] == 2, f"seed {seed}: {stats['columns']}"


# --------------------------------------------------------------------------
# grouping
# --------------------------------------------------------------------------

@check("paragraphs are not welded together")
def _():
    # The gap threshold used to be `line_height * 1.6`, which demanded 17pt
    # when paragraphs sit 9pt apart. Recall was 0.53 and the output still
    # looked entirely plausible.
    elements, _, truth = analyse(("two-column",), seed=42)
    expected = len([t for t in truth if t.order])
    got = len(flow(elements))
    assert got >= expected * 0.85, f"{got} elements for {expected} in truth"


@check("the grouping threshold comes from the page, not a constant")
def _():
    tight = [layout.Line(f"line {i}", (54, 100 + i * 10, 300, 108 + i * 10),
                         9.5, False, "helv") for i in range(6)]
    assert len(layout.group_lines(tight, 9.5)) == 1
    spaced = [layout.Line(f"line {i}", (54, 100 + i * 10, 300, 108 + i * 10),
                          9.5, False, "helv") for i in range(3)]
    spaced += [layout.Line(f"line {i}", (54, 200 + i * 10, 300, 208 + i * 10),
                           9.5, False, "helv") for i in range(3)]
    assert len(layout.group_lines(spaced, 9.5)) == 2


# --------------------------------------------------------------------------
# classification
# --------------------------------------------------------------------------

@check("element types are right on every generated layout")
def _():
    scores = []
    for kind in synth.LAYOUTS:
        elements, stats, truth = analyse((kind,))
        scores.append(metrics.score_page(truth, elements, stats["coverage"]))
    summary = metrics.aggregate(scores)
    assert summary["type_accuracy"] >= 0.98, summary["confusion"]
    assert summary["recall"] >= 0.95, summary["missed_by_type"]


@check("body size is measured on prose, not on table cells")
def _():
    # Table cells are a point or two smaller. Including them dragged the median
    # down far enough that ordinary paragraphs scored as headings on every
    # two-column page that also had a table.
    elements, stats, _ = analyse(("figure-table",))
    assert 9.0 <= stats["body_size"] <= 10.0, stats["body_size"]


@check("a caption is recognised by its lead, not only by its size")
def _():
    elements, _, _ = analyse(("figure-table",))
    captions = [e for e in flow(elements) if e.type == "caption"]
    assert len(captions) >= 2, [e.type for e in flow(elements)]
    assert any(c.text.lower().startswith("figure") for c in captions)
    assert any(c.text.lower().startswith("table") for c in captions)


# --------------------------------------------------------------------------
# tables
# --------------------------------------------------------------------------

@check("a ruled table is delegated to PyMuPDF and comes back exact")
def _():
    elements, _, truth = analyse(("figure-table",))
    found = [e for e in elements if e.type == "table"]
    expected = [t for t in truth if t.type == "table"][0]
    assert len(found) == 1, len(found)
    assert found[0].meta["detector"] == "lines"
    assert found[0].meta["rows"] == expected.meta["rows"]
    assert found[0].meta["cols"] == expected.meta["cols"]


@check("an unruled table is found, which find_tables cannot do")
def _():
    doc, truth = build(("unruled-table",), seed=5)
    try:
        page = doc[0]
        assert not page.find_tables(strategy="lines").tables, \
            "PyMuPDF found it after all; this test no longer measures anything"
        found = [e for e in layout.analyse_page(page)[0] if e.type == "table"]
    finally:
        doc.close()
    expected = [t for t in truth[0] if t.type == "table"][0]
    assert len(found) == 1, len(found)
    assert found[0].meta["detector"] == "alignment"
    assert found[0].meta["cols"] == expected.meta["cols"], \
        f"{found[0].meta['cols']} cols, truth {expected.meta['cols']}"


@check("two columns of prose are not mistaken for a table")
def _():
    # The false positive the x_range constraint exists for: run the alignment
    # detector across a whole two-column page and the two columns read as two
    # perfectly aligned cells repeated down the page. Three tables on a page
    # with none.
    for seed in (42, 43, 44):
        elements, stats, _ = analyse(("two-column",), seed=seed)
        assert stats["tables"] == 0, f"seed {seed}: {stats['tables']} phantom tables"


@check("PyMuPDF's text strategy is genuinely unusable here")
def _():
    # Justifies the module existing rather than calling find_tables(text).
    doc, _ = build(("unruled-table",), seed=5)
    try:
        found = doc[0].find_tables(strategy="text").tables
    finally:
        doc.close()
    assert found, "nothing found at all"
    assert found[0].row_count > 8, \
        f"{found[0].row_count} rows -- it no longer swallows the page"


# --------------------------------------------------------------------------
# the generator itself
# --------------------------------------------------------------------------

@check("ground-truth boxes are ink, not the requested rectangle")
def _():
    # A one-word heading requested in a 504x19 box renders as ~51x13 of ink.
    # Labelling the request made every correct detection score IoU < 0.5, and
    # the evaluation reported 28 missed headings and 28 invented ones in the
    # same places.
    doc, truth = build(("single",))
    try:
        page = doc[0]
        heading = [t for t in truth[0] if t.type == "heading"][0]
        assert heading.bbox[2] - heading.bbox[0] < 300, heading.bbox
        found = [l for l in layout.page_lines(page)
                 if l.text.strip() == heading.text.strip()]
        assert found and metrics.iou(found[0].bbox, heading.bbox) > 0.7
    finally:
        doc.close()


@check("the generator leaves no ink it did not label")
def _():
    # It used to paint white rectangles while searching for a font size that
    # fits. They survived into the PDF as vector drawings and the figure
    # detector correctly reported a page-wide figure behind every paragraph.
    doc, _ = build(("single",))
    try:
        figures = layout.figure_regions(doc[0])
    finally:
        doc.close()
    assert figures == [], f"{len(figures)} phantom figures on a text-only page"


# --------------------------------------------------------------------------
# metrics
# --------------------------------------------------------------------------

@check("kendall tau punishes an interleaved order properly")
def _():
    assert metrics.kendall_tau([1, 2, 3, 4], [1, 2, 3, 4]) == 1.0
    assert metrics.kendall_tau([1, 2, 3, 4], [4, 3, 2, 1]) == -1.0
    interleaved = metrics.kendall_tau([1, 2, 3, 4, 5, 6], [1, 4, 2, 5, 3, 6])
    assert 0.2 < interleaved < 0.8, interleaved


@check("type accuracy alone cannot hide a missed page")
def _():
    truth = [_T("paragraph", (0, 0, 100, 20), 1), _T("paragraph", (0, 30, 100, 50), 2),
             _T("heading", (0, 60, 100, 70), 3)]
    predicted = [_T("paragraph", (0, 0, 100, 20), 1)]
    score = metrics.score_page(truth, predicted)
    assert score["type_accuracy"] == 1.0        # flattering, and true
    assert score["recall"] < 0.4                # which is why recall is beside it


class _T:
    def __init__(self, type, bbox, order):
        self.type, self.bbox, self.order, self.text = type, bbox, order, ""


# --------------------------------------------------------------------------
# Phase 5: prove the suite fails on the code it was written against
# --------------------------------------------------------------------------

def _old_group_lines(lines, body):
    """Gap threshold as a multiple of line height. Welded paragraphs together."""
    blocks, current = [], []
    for line in lines:
        if not current:
            current = [line]
            continue
        previous = current[-1]
        gap = line.bbox[1] - previous.bbox[3]
        leading = max(previous.bbox[3] - previous.bbox[1], 1.0)
        style = (abs(line.size - previous.size) > 0.6
                 or line.bold != previous.bold)
        disjoint = (line.bbox[0] > previous.bbox[2] or line.bbox[2] < previous.bbox[0])
        if gap > leading * 1.6 or style or disjoint:
            blocks.append(current)
            current = [line]
        else:
            current.append(line)
    if current:
        blocks.append(current)
    return blocks


def _old_xy_cut(items, depth=0, max_depth=6):
    """Horizontal cut first. Interleaved every two-column page."""
    if len(items) <= 1 or depth >= max_depth:
        return list(items)
    for axis in (1, 0):
        lo_i, hi_i = (1, 3) if axis else (0, 2)
        ordered = sorted(items, key=lambda it: it[0][lo_i])
        reach = ordered[0][0][hi_i]
        best, best_gap = None, 0.0
        for i in range(1, len(ordered)):
            gap = ordered[i][0][lo_i] - reach
            if gap > best_gap:
                best_gap, best = gap, i
            reach = max(reach, ordered[i][0][hi_i])
        if best is not None and best_gap >= (4.0 if axis else layout.MIN_GUTTER_PT):
            return (_old_xy_cut(ordered[:best], depth + 1, max_depth)
                    + _old_xy_cut(ordered[best:], depth + 1, max_depth))
    return sorted(items, key=lambda it: (round(it[0][1], 1), it[0][0]))


def _old_column_bounds(lines, page_width):
    """"Empty for most of the page height." Called a table's gaps a gutter."""
    if len(lines) < 6:
        return [(0.0, page_width)]
    top = min(l.bbox[1] for l in lines)
    bottom = max(l.bbox[3] for l in lines)
    height = max(bottom - top, 1.0)
    step, n = 2.0, int(page_width / 2.0) + 1
    occupied = [0.0] * n
    for line in lines:
        lo, hi = int(line.bbox[0] / step), min(int(line.bbox[2] / step) + 1, n)
        for i in range(lo, hi):
            occupied[i] += line.bbox[3] - line.bbox[1]
    runs, start = [], None
    for i in range(n):
        if occupied[i] < height * 0.12:
            start = i if start is None else start
        else:
            if start is not None and (i - start) * step >= layout.MIN_GUTTER_PT:
                runs.append((start * step, i * step))
            start = None
    left = min(l.bbox[0] for l in lines)
    right = max(l.bbox[2] for l in lines)
    inner = [r for r in runs if r[0] > left + 1 and r[1] < right - 1]
    if not inner:
        return [(left, right)]
    bounds, cursor = [], left
    for lo, hi in inner:
        bounds.append((cursor, lo))
        cursor = hi
    bounds.append((cursor, right))
    return [b for b in bounds if b[1] - b[0] > 40] or [(left, right)]


REGRESSIONS = {
    "group_lines": (_old_group_lines,
                    ("paragraphs are not welded together",
                     "element types are right on every generated layout")),
    "xy_cut": (_old_xy_cut,
               ("a two-column page reads down one column then the other",)),
    "column_bounds": (_old_column_bounds,
                      ("a table's internal whitespace is not a column gutter",
                       "an unruled table is found, which find_tables cannot do")),
}


def verify_suite_is_not_decorative():
    by_name = dict(_results)
    lines, total_caught = [], 0
    for name, (old, targets) in REGRESSIONS.items():
        original = getattr(layout, name)
        setattr(layout, name, old)
        try:
            caught = 0
            for target in targets:
                try:
                    by_name[target]()
                except AssertionError:
                    caught += 1
        finally:
            setattr(layout, name, original)
        total_caught += caught
        lines.append(f"  pre-fix {name:<15} {caught}/{len(targets)} of its tests fail")
    return lines, total_caught


def main():
    failed = 0
    for name, fn in _results:
        try:
            fn()
            print(f"PASS  {name}")
        except AssertionError as exc:
            failed += 1
            print(f"FAIL  {name}\n      {exc}")
    print(f"\n{len(_results) - failed}/{len(_results)} passed")

    print("\nagainst the pre-fix implementations:")
    lines, caught = verify_suite_is_not_decorative()
    print("\n".join(lines))
    if caught < len(REGRESSIONS):
        print("the suite does not detect every bug it was written for")
        failed += 1
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
